# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t808h_XjkqKCOVt0FaMJRBji2ZANxvCS
"""

from google.colab import output
output.enable_custom_widget_manager()

import time
import ipywidgets as w
from IPython.display import display, clear_output

BOSS_LINE = "😡 JEFE: <b>TU PUESTO PARECE QUE PRONTO QUEDARÁ VACANTE</b>"
TIME_LIMIT = 60  # 1 minuto por pregunta

state = {
    "level": 0,
    "level_start": None,  # momento en que inició el nivel actual
}

def boss_warning(extra_html=""):
    return f"""
    <div style="margin-top:10px; padding:10px; border:1px solid #ddd; border-radius:10px;">
      {BOSS_LINE}<br>
      {extra_html}
    </div>
    """

def start_level_timer():
    state["level_start"] = time.monotonic()

def time_left():
    if state["level_start"] is None:
        return TIME_LIMIT
    elapsed = time.monotonic() - state["level_start"]
    remaining = int(TIME_LIMIT - elapsed)
    return max(0, remaining)

def is_time_up():
    return time_left() <= 0

def show_screen(title, text, controls, show_timer_note=False):
    clear_output(wait=True)
    display(w.HTML(f"<h2>{title}</h2>"))
    if show_timer_note:
        display(w.HTML(
            "<div style='font-size:14px; padding:8px; border:1px solid #eee; border-radius:10px;'>"
            "<b>⏱️ Regla:</b> 60 segundos por pregunta. "
            "El tiempo se valida cuando respondes (sin reloj animado para evitar congelamiento en Colab)."
            "</div>"
        ))
    display(w.HTML(f"<div style='font-size:16px; line-height:1.45'>{text}</div>"))
    display(w.VBox(controls))

def timeout_screen(retry_level):
    btn_retry = w.Button(description="Reintentar este nivel")
    btn_restart = w.Button(description="Reiniciar juego")
    btn_retry.on_click(lambda _: go(retry_level))
    btn_restart.on_click(lambda _: go(0))
    show_screen(
        "⛔ TIEMPO AGOTADO",
        boss_warning("Se acabó el minuto. En auditoría, el tiempo también es evidencia."),
        [btn_retry, btn_restart],
        show_timer_note=False
    )

def guard_time_or_continue(retry_level):
    """Se llama justo antes de evaluar una respuesta."""
    if is_time_up():
        timeout_screen(retry_level)
        return False
    return True

def go(level):
    state["level"] = level

    # INTRO
    if level == 0:
        state["level_start"] = None
        btn = w.Button(description="INICIAR AUDITORÍA")
        btn.on_click(lambda _: go(1))
        show_screen(
            "AUDITORÍA FORENSE – NIC 16",
            """
            Son las 22:45. Usted es el auditor externo de <b>INDUSTRIAL ANDINA S.A.</b><br><br>
            Alerta anónima: <i>"Están manipulando activos fijos para inflar utilidades."</i><br><br>
            Regla: <b>1 minuto por pregunta</b>. Si falla… el jefe se entera.
            """,
            [btn],
            show_timer_note=False
        )
        return

    # NIVEL 1
    if level == 1:
        start_level_timer()
        msg = w.HTML("")

        def check(ans):
            if not guard_time_or_continue(1):
                return
            if ans == "Activo fijo":
                go(2)
            else:
                msg.value = boss_warning("Incorrecto. NIC 16: PPE si genera beneficios futuros y el costo es medible.")

        buttons = []
        for opt in ["Gasto", "Activo fijo", "Inventario", "Activo intangible"]:
            b = w.Button(description=opt)
            b.on_click(lambda _, o=opt: check(o))
            buttons.append(b)

        show_screen(
            "Nivel 1: Reconocimiento (NIC 16)",
            """
            La empresa compró una máquina por <b>$80.000</b> para usarla en producción durante 10 años.<br><br>
            ¿Cómo debe reconocerse según NIC 16?
            """,
            buttons + [msg],
            show_timer_note=True
        )
        return

    # NIVEL 2
    if level == 2:
        start_level_timer()
        inp = w.Text(description="Respuesta", placeholder="Ej: 88000")
        msg = w.HTML("")
        btn = w.Button(description="Verificar")

        def verify(_):
            if not guard_time_or_continue(2):
                return
            try:
                val = float(inp.value.strip())
                if abs(val - 88000) < 1e-6:
                    go(3)
                else:
                    msg.value = boss_warning("Incorrecto. Costo inicial = 80.000 + 5.000 + 3.000.")
            except:
                msg.value = boss_warning("Ingrese un número válido (solo números).")

        btn.on_click(verify)

        show_screen(
            "Nivel 2: Medición inicial",
            """
            La empresa incurrió en:<br>
            • Precio: 80.000<br>
            • Transporte: 5.000<br>
            • Instalación: 3.000<br><br>
            ¿Cuál es el <b>costo inicial</b> del activo?
            """,
            [inp, btn, msg],
            show_timer_note=True
        )
        return

    # NIVEL 3
    if level == 3:
        start_level_timer()
        msg = w.HTML("")
        b1 = w.Button(description="Sí")
        b2 = w.Button(description="No")

        def check(ans):
            if not guard_time_or_continue(3):
                return
            if ans == "No":
                go(4)
            else:
                msg.value = boss_warning("Incorrecto. Capacitación es gasto del periodo (no capitalizable).")

        b1.on_click(lambda _: check("Sí"))
        b2.on_click(lambda _: check("No"))

        show_screen(
            "Nivel 3: ¿Se capitaliza?",
            """
            La empresa pagó <b>$4.000</b> por <b>capacitación</b> del personal para operar la máquina.<br><br>
            ¿Se incluye en el costo del activo?
            """,
            [b1, b2, msg],
            show_timer_note=True
        )
        return

    # NIVEL 4
    if level == 4:
        start_level_timer()
        inp = w.Text(description="Deprec.", placeholder="Ej: 8000")
        msg = w.HTML("")
        btn = w.Button(description="Verificar")

        def verify(_):
            if not guard_time_or_continue(4):
                return
            try:
                val = float(inp.value.strip())
                if abs(val - 8000) < 1e-6:
                    go(5)
                else:
                    msg.value = boss_warning("Incorrecto. (88.000 − 8.000) / 10 = 8.000.")
            except:
                msg.value = boss_warning("Ingrese un número válido (solo números).")

        btn.on_click(verify)

        show_screen(
            "Nivel 4: Depreciación",
            """
            Datos del activo:<br>
            • Costo: 88.000<br>
            • Valor residual: 8.000<br>
            • Vida útil: 10 años<br><br>
            ¿Cuál es la <b>depreciación anual</b>?
            """,
            [inp, btn, msg],
            show_timer_note=True
        )
        return

    # NIVEL 5
    if level == 5:
        start_level_timer()
        msg = w.HTML("")

        def check(ans):
            if not guard_time_or_continue(5):
                return
            if ans == "NIC 16":
                go(6)
            else:
                msg.value = boss_warning("Incorrecto. La obligación de depreciar PPE corresponde a NIC 16.")

        buttons = []
        for opt in ["NIC 16", "NIC 2", "NIC 38", "NIC 1"]:
            b = w.Button(description=opt)
            b.on_click(lambda _, o=opt: check(o))
            buttons.append(b)

        show_screen(
            "Nivel 5: Hallazgo crítico",
            """
            Detecta que la empresa <b>no está depreciando</b> la máquina.<br><br>
            ¿Qué norma está siendo violada?
            """,
            buttons + [msg],
            show_timer_note=True
        )
        return

    # FINAL
    if level == 6:
        btn_restart = w.Button(description="Reiniciar")
        btn_restart.on_click(lambda _: go(0))
        show_screen(
            "✅ MISIÓN COMPLETADA",
            """
            Felicitaciones. Aplicó NIC 16 correctamente:<br>
            • Reconocimiento<br>
            • Medición inicial<br>
            • Costos no capitalizables<br>
            • Depreciación
            """,
            [btn_restart],
            show_timer_note=False
        )

go(0)